import { defineConfig, devices } from "@playwright/test";
import { cucumberReporter, defineBddConfig } from "playwright-bdd";
import os from "node:os";
import path from "node:path";

// Dedicated ports, never reused. A developer's own uvicorn on :8000 is writing
// to the real backend/data/crm.csv — the file the dashboard aggregates — and
// these tests drive the REAL /approve path, so reusing it would file test rows
// as approved client matters. The suite brings up its own pair instead.
const BACKEND = "http://localhost:8001";
const FRONTEND = "http://localhost:3100";

const TEST_CRM = path.join(os.tmpdir(), "legalflow-e2e-crm.csv");

// Gherkin compiles to Playwright specs, so the feature files are a readable
// surface over this runner rather than a second stack: same workers, same
// webServer boot, same traces. Regenerated by `bddgen` before every run.
const testDir = defineBddConfig({
  features: "features/**/*.feature",
  steps: "features/steps/**/*.ts",
});

export default defineConfig({
  testDir,
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: [
    [process.env.CI ? "github" : "list"],
    // The point of Gherkin: a report the compliance side can open and read,
    // scenario by scenario, without being handed a terminal.
    cucumberReporter("html", { outputFile: "cucumber-report.html" }),
  ],
  use: { baseURL: FRONTEND, trace: "on-first-retry" },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
  webServer: [
    {
      // The venv interpreter, so the suite does not depend on an activated shell.
      command: ".venv/bin/uvicorn app.main:app --port 8001",
      cwd: "../backend",
      url: `${BACKEND}/health`,
      // load_dotenv does not override real env vars, so these beat backend/.env.
      env: { STORAGE_BACKEND: "csv", CRM_CSV_PATH: TEST_CRM },
      reuseExistingServer: false,
      timeout: 60_000,
    },
    {
      command: `npx next dev --port 3100`,
      url: FRONTEND,
      env: { NEXT_PUBLIC_API_BASE_URL: BACKEND },
      reuseExistingServer: false,
      timeout: 120_000,
    },
  ],
});
